# Generated by Django 3.2.5 on 2022-07-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScamData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_name', models.CharField(max_length=20)),
                ('register_phone', models.CharField(max_length=30)),
                ('site_name', models.CharField(max_length=40)),
                ('transaction', models.CharField(max_length=20)),
                ('object_name', models.CharField(max_length=100)),
                ('site_link', models.CharField(max_length=1000)),
                ('yong_id', models.CharField(max_length=30)),
                ('yong_account', models.IntegerField()),
                ('account_name', models.CharField(max_length=10)),
                ('trans_money', models.IntegerField()),
                ('trans_date', models.DateTimeField()),
                ('trans_phone', models.IntegerField()),
                ('trans_sex', models.CharField(max_length=10)),
                ('trans_location', models.CharField(max_length=20)),
            ],
        ),
    ]
