# Generated by Django 3.2.5 on 2022-07-20 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamdata',
            name='yong_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.offender'),
        ),
    ]
