# Generated by Django 3.2.5 on 2022-07-20 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('headquarters', '0001_initial'),
        ('public', '0002_alter_scamdata_yong_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamdata',
            name='account_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='headquarters.offender'),
        ),
        migrations.AlterField(
            model_name='scamdata',
            name='yong_id',
            field=models.CharField(max_length=20),
        ),
    ]
