# Generated by Django 3.2.5 on 2022-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_auto_20220720_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='scamdata',
            name='bank_name',
            field=models.CharField(default='신한은행', max_length=20),
        ),
    ]
