# Generated by Django 3.2.5 on 2022-07-20 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_scamdata_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamdata',
            name='bank_name',
            field=models.CharField(max_length=20),
        ),
    ]
