# Generated by Django 3.2.5 on 2022-07-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20220721_0325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scamdata',
            name='h_area1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='scamdata',
            name='h_area2',
            field=models.IntegerField(),
        ),
    ]
